const mongoose = require('mongoose');

/**
 * UserInterest
 *
 * Stores discrete interest-selection events.
 * Created once at signup (source: 'signup') and again whenever the user
 * manually updates their preferences (source: 'manual_update').
 *
 * This is intentionally separate from User.topicScores:
 *   - User.topicScores  → continuous numeric score, updated automatically by interactions
 *   - UserInterest      → discrete snapshot of explicit user choices, used for audit,
 *                         A/B testing, and cold-start fallback when topicScores is thin
 *
 * The InterestHistory model (see InterestHistory.js) records diffs between snapshots.
 */

const VALID_TOPICS = [
  'AI',
  'Machine Learning',
  'Finance',
  'Sports',
  'Health',
  'Programming',
  'Science',
  'Politics',
  'Business',
  'Design',
  'Travel',
  'Food',
  'Technology',
  'Environment',
  'Entertainment',
  'Education',
];

const UserInterestSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    /**
     * The explicit list of topics the user selected.
     * At least 1 required; 3+ recommended for meaningful recommendations.
     */
    topics: {
      type: [String],
      required: [true, 'Topics are required'],
      validate: [
        {
          validator: (v) => v.length >= 1,
          message: 'At least one topic must be selected',
        },
        {
          validator: (v) => v.every((t) => VALID_TOPICS.includes(t)),
          message: `Topics must be one of: ${VALID_TOPICS.join(', ')}`,
        },
      ],
    },

    /**
     * 384-dim unit-normalized embedding produced by mean-pooling the topic
     * label embeddings. Generated by the Python Embedding Service (:8001)
     * immediately after the user submits interests.
     *
     * Stored here as a historical record; the live version lives in User.profileEmbedding.
     */
    embeddingSnapshot: {
      type: [Number],
      default: [],
      validate: {
        validator: (v) => v.length === 0 || v.length === 384,
        message: 'embeddingSnapshot must be empty or exactly 384 dimensions',
      },
    },

    /**
     * What triggered this interest record.
     *   signup         → first selection immediately after account creation
     *   manual_update  → user revisited the interest settings page
     *   admin_seed     → seeded programmatically during testing or migration
     */
    source: {
      type: String,
      enum: ['signup', 'manual_update', 'admin_seed'],
      default: 'signup',
    },

    /**
     * True while this snapshot is the active preference set.
     * When a user updates interests, the previous record is set to isActive=false
     * and a new one is created with isActive=true.
     */
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    /**
     * Free-form metadata — device type, app version, A/B cohort, etc.
     * Not queried; stored for analytics pipelines.
     */
    meta: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true, versionKey: false },
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────

UserInterestSchema.index({ userId: 1, isActive: 1 });
UserInterestSchema.index({ userId: 1, createdAt: -1 });

// ── Static helpers ────────────────────────────────────────────────────────────

/**
 * Deactivate all existing interest records for a user, then create a new active one.
 * Call this on both signup (after the embedding is ready) and manual updates.
 *
 * @param {mongoose.Types.ObjectId} userId
 * @param {string[]} topics
 * @param {number[]} embeddingSnapshot  - 384-dim vector from Python service
 * @param {'signup'|'manual_update'|'admin_seed'} source
 * @returns {Promise<import('mongoose').Document>}
 */
UserInterestSchema.statics.replaceForUser = async function (
  userId,
  topics,
  embeddingSnapshot = [],
  source = 'manual_update'
) {
  // Deactivate previous records
  await this.updateMany({ userId, isActive: true }, { $set: { isActive: false } });

  // Create new active record
  return this.create({ userId, topics, embeddingSnapshot, source, isActive: true });
};

/**
 * Return the single active interest record for a user.
 * @param {mongoose.Types.ObjectId} userId
 * @returns {Promise<import('mongoose').Document|null>}
 */
UserInterestSchema.statics.getActive = function (userId) {
  return this.findOne({ userId, isActive: true }).sort({ createdAt: -1 });
};

/**
 * Expose the canonical list of valid topics so routes can validate input
 * without importing this file's internals directly.
 */
UserInterestSchema.statics.VALID_TOPICS = VALID_TOPICS;

const UserInterest = mongoose.model('UserInterest', UserInterestSchema);

module.exports = UserInterest;